"""
sft_train.py — Stage 1b: Supervised fine-tuning on pseudo-parallel SFT corpus.

Fine-tunes the student Llama-3.2-3B on the (source, best_rewrite) pairs
generated by sft_data_gen.py. This SFT warmup:
  - Narrows the RL search space before reward optimisation begins.
  - Enforces consistent output formatting.
  - Teaches the model to condition on style references and outlier hints.

Paper §4.3: LoRA adapters inserted in q_proj, k_proj, o_proj (SFT stage only).
The RL stage (train.py) extends this to all 7 projection layers.

Run after sft_data_gen.py:
    python sft_train.py --data clean_data/yelp_sft_pairs.csv --output yelp_sft_stage1
"""

import argparse
import pandas as pd
from unsloth import FastLanguageModel
from trl import SFTConfig, SFTTrainer

from dataset import get_sft_data
from config import BASE_MODEL, max_seq_length, lora_rank


def main():
    parser = argparse.ArgumentParser(
        description="Stage 1b: SFT fine-tuning on pseudo-parallel corpus."
    )
    parser.add_argument("--data", default="clean_data/yelp_sft_pairs.csv",
                        help="Path to CSV produced by sft_data_gen.py.")
    parser.add_argument("--output", default="yelp_sft_stage1",
                        help="Directory to save the fine-tuned model.")
    parser.add_argument("--base_model", default=BASE_MODEL,
                        help="Base model to fine-tune (overrides config.BASE_MODEL).")
    parser.add_argument("--epochs", type=int, default=3,
                        help="Number of SFT training epochs.")
    parser.add_argument("--lr", type=float, default=2e-4,
                        help="Learning rate.")
    args = parser.parse_args()

    print(f"Loading SFT data from: {args.data}")
    df = pd.read_csv(args.data)
    required_cols = {"review", "answer"}
    if not required_cols.issubset(df.columns):
        raise ValueError(f"SFT data must contain columns: {required_cols}")

    data_list = [
        {
            "review": row["review"],
            "answer": row["answer"],
            "ref_text": row.get("ref_text", None),
            "is_outlier": bool(row.get("is_outlier", False)),
        }
        for _, row in df.iterrows()
    ]
    print(f"Loaded {len(data_list)} training pairs.")

    # ── Load base model ───────────────────────────────────────────────────────
    print(f"Loading base model: {args.base_model}")
    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name=args.base_model,
        max_seq_length=max_seq_length,
        load_in_4bit=True,
        max_lora_rank=lora_rank,
    )

    # Paper §4.3: SFT uses q_proj, k_proj, o_proj only.
    # RL stage (train.py) adds the remaining MLP projection layers.
    model = FastLanguageModel.get_peft_model(
        model,
        r=lora_rank,
        target_modules=["q_proj", "k_proj", "o_proj"],
        lora_alpha=lora_rank,
        use_gradient_checkpointing=True,
        random_state=3407,
    )

    # ── Build SFT dataset (includes style ref + outlier hint in prompt) ───────
    sft_dataset = get_sft_data(data_list, tokenizer)

    # ── Train ─────────────────────────────────────────────────────────────────
    trainer = SFTTrainer(
        model=model,
        processing_class=tokenizer,
        train_dataset=sft_dataset,
        args=SFTConfig(
            dataset_text_field="text",
            per_device_train_batch_size=2,
            gradient_accumulation_steps=4,
            num_train_epochs=args.epochs,
            learning_rate=args.lr,
            lr_scheduler_type="cosine",
            warmup_ratio=0.05,
            output_dir=args.output,
            logging_steps=10,
            save_steps=500,
            report_to="wandb",
            max_seq_length=max_seq_length,
        ),
    )
    trainer.train()

    model.save_pretrained(args.output)
    tokenizer.save_pretrained(args.output)
    print(f"SFT model saved to: {args.output}")
    print(f"Next step: set BASE_MODEL = \"{args.output}\" in config.py, then run train.py")


if __name__ == "__main__":
    main()
